#!/usr/bin/env python3
"""
Agent Feature Workflow — 极强自动化工单脚本

用法：
    python agent-feature.py "导出 support_log 为 CSV"

自动完成：
    1. 自动创建 Issue（Epic/Feature/Task 自动拆分）
    2. 创建开发分支
    3. TDD 测试 + 代码
    4. Commit（Conventional Commits）
    5. 自动生成 PR + 勾选 markdown checkbox
    6. 检查文档同步（模拟 check-docs-sync.sh）
    7. 等待 CI 通过 + 推荐合并

零交互：你只输一句需求，后面全自动化（直到虚县手最后合并）
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path
from typing import Optional, List, Tuple
import json


# ===== 配置 =====

TEAM_SCRIPTS_DIR = Path(__file__).parent.parent

# 核心文档检查清单（5 份：与 professional-ai-coding-workflow 对齐）
CORE_DOCUMENTS = [
    "docs/PRD.md",              # 产品需求文档
    "CHANGELOG.md",             # 版本更新日志
    "README.md",                # 项目总览
    "docs/AGENTS.md",           # AI 角色注入
    "docs/INTEGRATION.md"       # API 端点清单
]

DEFAULT_BRANCH = "main"


# ===== 工具函数 =====

def run_cmd(cmd: List[str], workdir: Optional[Path] = None, check=True) -> subprocess.CompletedProcess:
    """运行命令并返回结果"""
    print(f"  $ {' '.join(cmd)}")
    if workdir:
        print(f"  (在 {workdir})")
    result = subprocess.run(cmd, cwd=workdir, capture_output=True, text=True, check=False)
    if result.returncode != 0 and check:
        print(f"  ❌ 命令失败退出码: {result.returncode}")
        print(f"  stderr: {result.stderr}")
        raise subprocess.CalledProcessError(result.returncode, cmd, result.stdout, result.stderr)
    return result


def gh_command(args: List[str]) -> subprocess.CompletedProcess:
    """封装 gh CLI"""
    return run_cmd(["gh"] + args)


def get_current_branch() -> str:
    """获取当前分支"""
    result = run_cmd(["git", "branch", "--show-current"], check=False)
    return result.stdout.strip() or "main"


def has_uncommitted_changes() -> bool:
    """检查是否有未提交变更"""
    result = run_cmd(["git", "status", "--porcelain"], check=False)
    return bool(result.stdout.strip())


def check_docs_sync(project_dir: Path) -> Tuple[bool, List[str]]:
    """
    检查文档同步（模拟 check-docs-sync.sh 的逻辑）

    返回：
        (docs_changed, files_to_update)
    """
    result = run_cmd(["git", "diff", f"origin/{DEFAULT_BRANCH}", "--name-only", "--pretty=format:"],
                     workdir=project_dir, check=False)

    changed_files = [f.strip() for f in result.stdout.strip().split("\n") if f.strip()]
    docs_to_update = [f for f in changed_files if any(doc in f for doc in PROJECT_REGENGERY_FILES)]

    return len(docs_to_update) > 0, docs_to_update


def create_issue(auto_issue_url: str) -> int:
    """
    创建 Issue

    返回 Issue number
    """
    # 从 GitHub URL 提取 number，如 https://github.com/.../issues/123
    issue_number = auto_issue_url.split("/")[-1]
    return int(issue_number)


def draft_changelog(project_dir: Path) -> str:
    """
    自动起草 CHANGELOG（调用 scripts/draft-changelog.sh）

    返回：CHANGELOG 内容
    """
    result = run_cmd(["bash", str(TEAM_SCRIPTS_DIR / "draft-changelog.sh"),
                     "--output=/tmp/autogenerated-changelog.md"],
                     workdir=project_dir, check=False)

    chlog_path = Path("/tmp/autogenerated-changelog.md")
    if chlog_path.exists():
        changelog = chlog_path.read_text()
        return changelog
    else:
        return "# AUTO-GENERATED CHANGELOG\n\n暂无变更\n"


def generate_pr_body(feature_key: str, change_count: int, docs_updated: bool) -> str:
    """
    生成 PR body（含 markdown checkbox）

    支持的 checkbox：
        ✅ docs/README.md 已更新
        ✅ docs/CHANGELOG.md 已更新
        ✅ 所有文档变更已完成
    """
    lines = [
        f"## {feature_key}",
        "",
    ]

    if docs_updated:
        lines.extend([
            "### 已完成",
            "✅ docs/README.md 已更新",
            "✅ docs/CHANGELOG.md 已更新",
            "✅ 所有文档变更已完成",
            "",
            "### 注意事项",
            "- 本 PR 包含文档更新，通过文档同步门禁",
            "- 无需手动添加 `bypass-doc-gate` label",
        ])
    else:
        lines.extend([
            "### 已完成",
            "⚠️ 代码已提交，但未检测到文档变更",
            "",
            "### 待补外部：",
            "- docs/README.md（如用户可见）",
            "- docs/CHANGELOG.md（必须补）",
            "",
            "### 备注：",
            "- 请手动完成文档更新后重新提交 PR",
            "- 或给 owner/reviewer 加 `bypass-doc-gate` label（紧急情况）",
        ])

    lines.extend([
        "",
        "---",
        self.format() if hasattr(self, 'format') else "",
    ])

    return "\n".join(lines)


# ===== 核心流程 =====

def auto_create_issue(feature_key: str, feature_description: List[str]) -> int:
    """
    自动创建 Issue

    feature_key: issue 标题的关键词（如 "export-support-log-csv"）
    feature_description: 详细描述列表（如 ["导出支持日志为 CSV", "支持分页", "支持按时间范围筛选"]）
    """
    title = f"[{feature_key}] {feature_description[0]}"
    body = "## 需求说明\n\n" + "\n".join(f"- {item}" for item in feature_description)

    print(f"\n📝 自动创建 Issue: {title}")
    result = gh_command([
        "issue", "create",
        "--title", title,
        "--body", body,
        "--label", "feature"
    ])

    result.check_output()  # 会抛出异常如果失败

    # 从结果中提取 URL，如 https://github.com/.../issues/123
    issue_url = result.stdout.strip()
    issue_number = create_issue(issue_url)

    print(f"  ✅ Issue #{issue_number} 已创建: {issue_url}")

    return issue_number


def auto_create_branch(feature_key: str) -> str:
    """
    自动创建分支

    feature_key: 如 feat/export-support-log-csv
    """
    branch_name = f"{feature_key}/v1"
    print(f"\n🌿 自动创建分支: {branch_name}")

    run_cmd(["git", "checkout", DEFAULT_BRANCH])
    run_cmd(["git", "pull", "origin", DEFAULT_BRANCH])
    run_cmd(["git", "checkout", "-b", branch_name])

    print(f"  ✅ 分支 {branch_name} 已创建")
    return branch_name


def auto_write_code(project_dir: Path, feature_key: str, feature_description: List[str]):
    """
    模拟 TDD 自动写代码（示例逻辑）

    real 使用场景下会调用你的 skill 或 MCP
    """
    print(f"\n💻 自动写代码: {feature_key}")

    # 这里只是示例，你需要改成你真实的开发流程
    # 例如：
    # - write_test() → 这一步实际上是调用你的 TDD skill
    # - write_code() → 调用你的 coding agent

    # 示例：写入一个简单的示例文件
    example_file = project_dir / "examples" / f"{feature_key.replace('-', '_')}.py"
    example_file.parent.mkdir(exist_ok=True)

    example_content = f'''"""
{feature_key} 示例实现

功能：
{chr(10).join(f"- {desc}" for desc in feature_description)}

用法示例：
    from examples.{feature_key.replace('-', '_')} import ExportCSV

    exporter = ExportCSV()
    exporter.run()
"""

import csv
from datetime import datetime


class ExportCSV:
    """导出支持日志为 CSV"""

    def __init__(self, log_file: str = "support.log", output_csv: str = "export.csv"):
        self.log_file = log_file
        self.output_csv = output_csv

    def run(self, start_date: str = None, end_date: str = None):
        """执行导出操作"""
        print(f"开始导出从 {start_date or '全部'} 到 {end_date or '全部'} 的支持日志...")

        with open(self.log_file, 'r', encoding='utf-8') as f_in:
            logs = [line.strip() for line in f_in.readlines() if line.strip()]

        if not logs:
            print("警告：日志文件为空")
            return

        with open(self.output_csv, 'w', encoding='utf-8', newline='') as f_out:
            writer = csv.writer(f_out)
            writer.writerow(["时间", "用户", "问题", "描述"])
            writer.writerows(logs)

        print(f"✅ 已导出到 {self.output_csv}（{len(logs)} 条记录）")


if __name__ == "__main__":
    ExportCSV().run()
'''

    example_file.write_text(example_content, encoding='utf-8')
    print(f"  ✅ 示例代码已生成: {example_file.relative_to(project_dir)}")

    # 创建对应的测试文件
    test_file = project_dir / "tests" / f"test_{feature_key.replace('-', '_')}.py"
    test_file.parent.mkdir(exist_ok=True)

    test_content = f'''"""
测试模块：{feature_key}

功能：
{chr(10).join(f"- {desc}" for desc in feature_description)}
"""

import pytest
from examples.{feature_key.replace('-', '_')} import ExportCSV


def test_export_csv_basic():
    """测试基础导出功能"""
    exporter = ExportCSV()

    # 可以在这里添加真实的测试逻辑
    assert hasattr(exporter, 'run')
'''

    test_file.write_text(test_content, encoding='utf-8')
    print(f"  ✅ 测试文件已生成: {test_file.relative_to(project_dir)}")


def auto_commit(project_dir: Path, feature_key: str) -> str:
    """
    自动 Commit（Conventional Commits）

    返回：commit message
    """
    message = f"feat({feature_key}): 实现导出 CSV 功能\n\n"
    message += "- 添加导出 CSV 类\n"
    message += "- 添加单元测试\n"

    print(f"\n💾 自动提交: {message}")

    run_cmd(["git", "add", "."], workdir=project_dir)
    run_cmd(["git", "commit", "-m", message], workdir=project_dir)

    print("  ✅ Commit 已提交")
    return message


def auto_create_pr(project_dir: Path, feature_key: str, docs_updated: bool) -> Tuple[bool, str]:
    """
    自动创建 PR

    返回：(成功状态, PR URL) 或 (False, 错误信息)
    """
    print(f"\n🔗 自动创建 PR ({feature_key})")

    change_type = "docs" if docs_updated else "feat"
    title = f"[{change_type}] {feature_key}: 实现导出 CSV 功能"

    # 生成 PR body（含自动勾选的 checkbox）
    # 注意：gh CLI 的 --body 支持的多行需要 --body-file
    pr_description = generate_pr_body(feature_key, "", docs_updated)
    pr_description_file = project_dir / ".temp_pr_body.md"
    pr_description_file.write_text(pr_description, encoding='utf-8')

    try:
        result = gh_command([
            "pr", "create",
            "--title", title,
            "--body-file", str(pr_description_file),
            "--base", DEFAULT_BRANCH,
            "--head", f"@me:{feature_key}/v1"
        ])

        result.check_output()

        pr_url = result.stdout.strip()
        print(f"  ✅ PR 已创建: {pr_url}")

        return True, pr_url

    except subprocess.CalledProcessError as e:
        if "A pull request already exists" in e.stderr:
            print("  ⚠️  PR 已存在，跳过")
            return False, ""
        raise


def auto_wait_and_check_ci(project_dir: Path, feature_key: str, docs_updated: bool):
    """
    自动等待 CI 通过 + 检查门禁

    docs_updated: 如果文档已改，则这是"正常流程"
    """
    print(f"\n⏳ 等待 CI 运行...")

    max_attempts = 30
    wait_time = 30  # 秒

    for attempt in range(max_attempts):
        print(f"  [尝试 {attempt + 1}/{max_attempts}] 等待 {wait_time} 秒...")
        run_cmd(["sleep", str(wait_time)], timeout=wait_time + 10)

        result = gh_command([
            "pr", "view", "--json checks", "--jq '.checks'"], check=False)

        # 这里简化判断，实际需要解析 JSON
        # 应该有类似：status = "completed/running/queued"

    print("  ❌ CI 检查失败")
    return False


def auto_check_docs_sync(project_dir: Path) -> Tuple[bool, List[str]]:
    """
    检查文档同步（模拟 check-docs-sync.sh）

    返回：(是否更新, 文档列表)
    """
    print(f"\n📄 检查文档同步...")

    docs_updated, docs_to_update = check_docs_sync(project_dir)

    if docs_updated:
        print(f"  ✅ 文档已更新: {docs_to_update}")
    else:
        print(f"  ❌ 未检测到文档变更")
        print(f"  建议：请手动更新 src/support_log_export/ 目录下的文档")

    return docs_updated, docs_to_update


def analyze_git_status(project_dir: Path) -> Tuple[bool, List[str]]:
    """
    分析 git 状态（手动调用 check-docs-sync.sh）

    返回：(是否更新, 文档列表)
    """
    # 这里先简化实现，实际应该调用 check-docs-sync.sh
    # 但由于我们的自动化目标是"零交互"，所以这里用模拟逻辑
    return auto_check_docs_sync(project_dir)


# ===== 主流程 =====

def main():
    parser = argparse.ArgumentParser(description="Agent Feature Workflow — 极强自动化工单脚本")
    parser.add_argument("feature_key", help="功能关键帧，如 export-support-log-csv")
    parser.add_argument("--description", nargs="+", default=[], help="功能描述（第一项为标题）")
    parser.add_argument("--project", default="prompt-engine", help="项目目录名（默认 prompt-engine）")
    parser.add_argument("--simulate", action="store_true", help="模拟运行（不实际创建 Issue/PR）")
    # 覆盖项目目录（让脚本可以通过 command line 覆盖）
    parser.add_argument("--workdir", help="工作目录")

    args = parser.parse_args()

    # 验证参数
    if not args.description:
        print("错误：请提供功能描述")
        sys.exit(1)

    # 确定工作目录
    if args.workdir:
        project_dir = Path(args.workdir)
    else:
        project_dir = Path(__file__).parent.parent / args.project

    if not project_dir.exists():
        print(f"错误：项目目录不存在: {project_dir}")
        sys.exit(1)

    print("=" * 70)
    print("🤖 Agent Feature Workflow — 极强自动化工单脚本")
    print("=" * 70)
    print(f"功能关键帧: {args.feature_key}")
    print(f"功能描述: {' '.join(args.description)}")
    print(f"工作目录: {project_dir}")

    # 检查是否已切换到项目的 main 分支
    current_branch = get_current_branch()

    if current_branch != "main":
        print(f"⚠️  当前不在 main 分支 ({current_branch})，将自动切换")
        run_cmd(["git", "checkout", "main"])

    # 拉取最新代码
    print(f"\n🔄 拉取最新代码...")
    current_branch = get_current_branch()
    # 自动匹配分支名称（优先 main，其次 master）
    target_branch = "main" if current_branch == "main" else "master"
    run_cmd(["git", "pull", "origin", target_branch], workdir=project_dir)

    # 自动创建 Issue
    if not args.simulate:
        issue_number = auto_create_issue(args.feature_key, args.description)
    else:
        issue_number = 9998  # 模拟号
        print(f"\n📝 自动创建 Issue（模拟）: #{issue_number}")

    # 自动创建分支
    branch_name = auto_create_branch(args.feature_key)

    # 自动写代码（TDD）
    print(f"\n🔍 进入目录: {project_dir}")
    auto_write_code(project_dir, args.feature_key, args.description)

    # 自动 Commit
    commit_message = auto_commit(project_dir, args.feature_key)

    # 分析文档同步
    docs_updated, docs_to_update = analyze_git_status(project_dir)

    # 自动创建 PR
    if not args.simulate:
        pr_success, pr_url = auto_create_pr(project_dir, args.feature_key, docs_updated)
        if not pr_success or not pr_url:
            print("❌ PR 创建失败或已存在")
            sys.exit(1)
    else:
        pr_url = f"https://github.com/Colinchiu007/{args.project}/pull/9999"
        docs_updated = False
        print(f"\n🔗 自动创建 PR（模拟）: {pr_url}")

    # 自动等待 CI + 检查门禁
    # 这里暂时简化，实际应该用 GitHub API 轮询 CI 状态
    print(f"\n⏳ 等待 CI 运行...")

    # 最终报告
    print("\n" + "=" * 70)
    print("✅ Agent Feature Workflow — 自动化工单完成")
    print("=" * 70)
    print(f"功能: {' '.join(args.description)}")
    print(f"Issue:  https://github.com/Colinchiu007/{args.project}/issues/{issue_number}")
    print(f"PR:     {pr_url}")
    print(f"分支:   {branch_name}")
    print(f"文件变更:")

    files_diff = run_cmd(["git", "diff", "--name-only", "origin/main"],
                        workdir=project_dir).stdout.strip().split("\n")
    for f in files_diff:
        print(f"  - {f}")

    if docs_updated:
        print(f"\n✅ 文档更新: {docs_to_update}")
        print("💡 可以直接在 GitHub 上合并 PR")
    else:
        print(f"\n⚠️  未检测到文档变更")
        print(f"💡 请在 GitHub 网页上手动更新 README.md/CHANGELOG.md，然后点击 'Re-run workflow' 重新触发 CI")

    # 清理临时文件
    (project_dir / ".temp_pr_body.md").unlink(missing_ok=True)


if __name__ == "__main__":
    main()