#!/usr/bin/env python3
"""
Agent Feature Workflow — 极强自动化工单脚本

用法：
    python agent-feature.py "导出 support_log 为 CSV"

自动完成：
    1. 自动创建 Issue（Epic/Feature/Task 自动拆分）
    2. 创建开发分支
    3. TDD 测试 + 代码
    4. Commit（Conventional Commits）
    5. 自动生成 PR + 勾选 markdown checkbox
    6. 检查文档同步（模拟 check-docs-sync.sh）
    7. 等待 CI 通过 + 推荐合并

零交互：你只输一句需求，后面全自动化（直到虚县手最后合并）
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path
from typing import Optional, List, Tuple
import json


# ===== 配置 =====

TEAM_SCRIPTS_DIR = Path(__file__).parent.parent

# 核心文档检查清单（5 份：与 professional-ai-coding-workflow 对齐）
CORE_DOCUMENTS = [
    "docs/PRD.md",              # 产品需求文档
    "CHANGELOG.md",             # 版本更新日志
    "README.md",                # 项目总览
    "docs/AGENTS.md",           # AI 角色注入
    "docs/INTEGRATION.md"       # API 端点清单
]

DEFAULT_BRANCH = "main"


# ===== 工具函数 =====

def run_cmd(cmd: List[str], workdir: Optional[Path] = None, check=True) -> subprocess.CompletedProcess:
    """运行命令并返回结果"""
    print(f"  $ {' '.join(cmd)}")
    if workdir:
        print(f"  (在 {workdir})")
    result = subprocess.run(cmd, cwd=workdir, capture_output=True, text=True, check=False)
    if result.returncode != 0 and check:
        print(f"  ❌ 命令失败退出码: {result.returncode}")
        print(f"  stderr: {result.stderr}")
        raise subprocess.CalledProcessError(result.returncode, cmd, result.stdout, result.stderr)
    return result


def gh_command(args: List[str]) -> subprocess.CompletedProcess:
    """封装 gh CLI"""
    return run_cmd(["gh"] + args)


def get_current_branch() -> str:
    """获取当前分支"""
    result = run_cmd(["git", "branch", "--show-current"], check=False)
    return result.stdout.strip() or "main"


def has_uncommitted_changes() -> bool:
    """检查是否有未提交变更"""
    result = run_cmd(["git", "status", "--porcelain"], check=False)
    return bool(result.stdout.strip())


def check_docs_sync(project_dir: Path, base_branch: str = "main") -> Tuple[bool, List[str]]:
    """
    检查文档同步（与 5 份核心文档对齐）

    返回：
        (docs_changed, files_to_update)
    """
    result = run_cmd(["git", "diff", f"origin/{base_branch}", "--name-only", "--pretty=format:"],
                     workdir=project_dir, check=False)

    changed_files = [f.strip() for f in result.stdout.strip().split("\n") if f.strip()]

    docs_to_update = []
    for file in CORE_DOCUMENTS:
        # 检查文件名（去除 docs/ 前缀）
        clean_file = file.replace("docs/", "")
        # 匹配：精确文件名 或 路径以这个文件结尾
        for f in changed_files:
            if f.endswith(clean_file) or f.split("/")[-1] == clean_file:
                docs_to_update.append(clean_file)
                break

    return len(docs_to_update) > 0, docs_to_update


def create_issue(auto_issue_url: str) -> int:
    """
    创建 Issue

    返回 Issue number
    """
    # 从 GitHub URL 提取 number，如 https://github.com/.../issues/123
    issue_number = auto_issue_url.split("/")[-1]
    return int(issue_number)


def draft_changelog(project_dir: Path) -> str:
    """
    自动起草 CHANGELOG（调用 scripts/draft-changelog.sh）

    返回：CHANGELOG 内容
    """
    result = run_cmd(["bash", str(TEAM_SCRIPTS_DIR / "draft-changelog.sh"),
                     "--output=/tmp/autogenerated-changelog.md"],
                     workdir=project_dir, check=False)

    chlog_path = Path("/tmp/autogenerated-changelog.md")
    if chlog_path.exists():
        changelog = chlog_path.read_text()
        return changelog
    else:
        return "# AUTO-GENERATED CHANGELOG\n\n暂无变更\n"


def generate_pr_body(feature_key: str, change_count: int, docs_updated: bool,
                     has_tests: bool = True, has_security_checks: bool = True) -> str:
    """
    生成 PR body（5 维 checkbox — 整合 professional-ai-coding-workflow）

    5 维检查：
        1. 变更类型（feat/fix/docs/refactor/test/chore）
        2. 通用检查清单（代码自审/无 console.log/无硬编码密钥/风格一致）
        3. 文档同步（5 份核心文档：PRD/CHANGELOG/README/AGENTS/INTEGRATION）
        4. 测试与质量（单元测试 / 无安全隐患）
        5. CI 门禁（bypass 标签 / 注意事项）
    """
    lines = [
        f"## PR: {feature_key}",
        "",
        "### 1️⃣ 变更类型",
        "- [ ] feat（新功能）",
        "- [ ] fix（Bug 修复）",
        "- [ ] docs（文档）",
        "- [ ] refactor（重构）",
        "- [ ] test（测试）",
        "- [ ] chore（配置/工具）",
        "",
        "### 2️⃣ 检查清单（4 维）",
        "- [ ] 代码自审通过",
        "- [ ] 无 console.log / print 残留",
        "- [ ] 无硬编码密钥（API_KEY / SECRET / PASSWORD / TOKEN）",
        "- [ ] 代码风格一致（通过 ruff / ESLint）",
        "",
    ]

    # 3️⃣ 文档同步（5 份核心文档）
    if docs_updated:
        lines.extend([
            "### 3️⃣ 文档同步（5 份核心文档）",
            "- [x] `docs/PRD.md` 已更新",
            "- [x] `CHANGELOG.md` 已更新",
            "- [x] `README.md` 已更新",
            "- [x] `docs/AGENTS.md` 已更新",
            "- [x] `docs/INTEGRATION.md` 已更新",
            "",
        ])
    else:
        lines.extend([
            "### 3️⃣ 文档同步（⚠️ 未检测到文档变更）",
            "请手动更新以下 5 份核心文档：",
            "- [ ] `docs/PRD.md`（如功能有 PRD）",
            "- [ ] `CHANGELOG.md`（必须补）",
            "- [ ] `README.md`（如用户可见）",
            "- [ ] `docs/AGENTS.md`（如涉及角色变更）",
            "- [ ] `docs/INTEGRATION.md`（如涉及 API 端点）",
            "",
        ])

    # 4️⃣ 测试与质量
    lines.extend([
        "### 4️⃣ 测试与质量",
        f"- [{'x' if has_tests else ' '}] 单元测试已写（{change_count} 个测试文件）",
        f"- [{'x' if has_security_checks else ' '}] 无安全隐患（无 console.log、硬编码密钥）",
        "",
    ])

    # 5️⃣ CI 门禁 + 注意事项
    if docs_updated:
        lines.extend([
            "### 5️⃣ CI 门禁",
            "- [x] 通过文档同步门禁",
            "- [x] 无需手动添加 `bypass-doc-gate` label",
            "",
            "### 📌 注意事项",
            "- 本 PR 包含 5 份核心文档更新",
            "- merge 前请 CTO/owner review",
        ])
    else:
        lines.extend([
            "### 5️⃣ CI 门禁（⚠️ 文档未同步）",
            "- [ ] **必须** 手动更新文档后，点击 PR 的 `Re-run workflow` 重新触发 CI",
            "- [ ] 或给 owner/reviewer 加 `bypass-doc-gate` label（紧急情况）",
            "",
            "### 📌 注意事项",
            "- 当前 PR 的 CI 会红灯（因为代码改了但文档没改）",
            "- merge 前请**先**补齐文档，再 Re-run workflow",
        ])

    lines.extend([
        "",
        "---",
        "",
        f"🤖 由 agent-feature.py 自动生成于 {Path(__file__).name}",
    ])

    return "\n".join(lines)


# ===== 核心流程 =====

def auto_create_issue(feature_key: str, feature_description: List[str],
                      issue_type: str = "feature") -> int:
    """
    自动创建 Issue（使用 issue-feature.md 模板）

    Args:
        feature_key: issue 标题的关键词（如 "export-support-log-csv"）
        feature_description: 详细描述列表（如 ["导出支持日志为 CSV", "支持分页", "支持按时间范围筛选"]）
        issue_type: issue 类型（feature/bug/chore/refactor/docs）

    Returns:
        Issue number
    """
    # 1. 选择模板
    template_map = {
        "feature": "issue-feature.md",
        "bug": "issue-bug.md",  # 可能不存在，回退到 feature
        "chore": "issue-feature.md",
        "refactor": "issue-feature.md",
        "docs": "issue-feature.md",
    }

    template_file = template_map.get(issue_type, "issue-feature.md")
    template_path = TEAM_SCRIPTS_DIR / "templates" / template_file

    # 2. 填充模板
    title = f"[{feature_key}] {feature_description[0]}"

    if template_path.exists():
        template = template_path.read_text(encoding='utf-8')

        try:
            body = template.format(
                title=title,
                description="\n".join(f"- **{item}**" for item in feature_description),
                type_label=issue_type,
                priority="P1",
                status="backlog"
            )
        except KeyError as e:
            # 模板不匹配，回退到简单格式
            print(f"  ⚠️  模板占位符 {e} 不存在，使用简单格式")
            body = "## 需求说明\n\n" + "\n".join(f"- **{item}**" for item in feature_description)
    else:
        # 模板不存在，使用简单格式
        body = "## 需求说明\n\n" + "\n".join(f"- **{item}**" for item in feature_description)

    # 3. 自动识别 feature_key 类型（推断 label）
    label_map = {
        "feature": "feature",
        "bug": "bug",
        "chore": "chore",
        "refactor": "refactor",
        "docs": "docs",
    }
    label = label_map.get(issue_type, "feature")

    print(f"\n📝 自动创建 Issue: {title}")
    print(f"   标签: {label} | 模板: {template_file}")

    result = gh_command([
        "issue", "create",
        "--title", title,
        "--body", body,
        "--label", label
    ])

    result.check_output()  # 会抛出异常如果失败

    # 从结果中提取 URL，如 https://github.com/.../issues/123
    issue_url = result.stdout.strip()
    issue_number = create_issue(issue_url)

    print(f"  ✅ Issue #{issue_number} 已创建: {issue_url}")

    return issue_number


def _sanitize_branch_name(name: str) -> str:
    """
    将任意字符串转为 git 合法分支名（只允许 ASCII 字母、数字、-、_、/）

    Args:
        name: 原始字符串（可能含中文、特殊字符）

    Returns:
        git 合法分支名（小写 + kebab-case）
    """
    import re
    # 1. 替换空白和特殊字符为 -
    sanitized = re.sub(r'[\s._]+', '-', name)
    # 2. 只保留 ASCII 字母、数字、-、_、/
    sanitized = re.sub(r'[^a-zA-Z0-9\-_/]', '', sanitized)
    # 3. 全部小写
    sanitized = sanitized.lower()
    # 4. 去除重复的 -
    sanitized = re.sub(r'-+', '-', sanitized)
    # 5. 去除首尾的 -
    sanitized = sanitized.strip('-')
    # 6. 限制长度
    if len(sanitized) > 50:
        sanitized = sanitized[:50]
    return sanitized


def auto_create_branch(feature_key: str, base_branch: str = "main") -> str:
    """
    自动创建分支

    feature_key: 如 feat/export-supported-log-csv（可能含中文，会被转 ASCII）
    base_branch: 基础分支（默认 main）
    """
    # 转换 feature_key 为合法分支名
    safe_feature_key = _sanitize_branch_name(feature_key)
    branch_name = f"{safe_feature_key}/v1"
    print(f"\n🌿 自动创建分支: {branch_name}")
    if branch_name != f"{feature_key}/v1":
        print(f"   (已转 ASCII: {feature_key} → {safe_feature_key})")

    # 检查是否已经在 base_branch
    current = get_current_branch()
    if current != base_branch:
        checkout_result = run_cmd(["git", "checkout", base_branch], check=False)
        if checkout_result.returncode != 0:
            print(f"  ⚠️  无法切换到 {base_branch}，使用当前分支 {current} 作为基础")
            base_branch = current
    else:
        print(f"  ✅ 已在 {base_branch} 分支上")

    # 拉取最新代码（失败时仅警告）
    pull_result = run_cmd(["git", "pull", "origin", base_branch], check=False)
    if pull_result.returncode != 0:
        print(f"  ⚠️  拉取失败，但继续创建分支")

    # 创建新分支
    run_cmd(["git", "checkout", "-b", branch_name])

    print(f"  ✅ 分支 {branch_name} 已创建")
    return branch_name


def auto_write_code(project_dir: Path, feature_key: str, feature_description: List[str]):
    """
    模拟 TDD 自动写代码（示例逻辑）

    real 使用场景下会调用你的 skill 或 MCP
    """
    print(f"\n💻 自动写代码: {feature_key}")

    # 这里只是示例，你需要改成你真实的开发流程
    # 例如：
    # - write_test() → 这一步实际上是调用你的 TDD skill
    # - write_code() → 调用你的 coding agent

    # 示例：写入一个简单的示例文件
    example_file = project_dir / "examples" / f"{feature_key.replace('-', '_')}.py"
    example_file.parent.mkdir(exist_ok=True)

    example_content = '''
"""
''' + feature_key + ''' 示例实现

功能：
''' + chr(10).join(f"- {desc}" for desc in feature_description) + '''

用法示例：
    from examples.''' + feature_key.replace('-', '_') + ''' import ExportCSV

    exporter = ExportCSV()
    exporter.run()
"""

import csv
from datetime import datetime


class ExportCSV:
    """导出支持日志为 CSV"""

    def __init__(self, log_file: str = "support.log", output_csv: str = "export.csv"):
        self.log_file = log_file
        self.output_csv = output_csv

    def run(self, start_date: str = None, end_date: str = None):
        """执行导出操作"""
        print("开始导出从 " + (start_date or "全部") + " 到 " + (end_date or "全部") + " 的支持日志...")

        with open(self.log_file, 'r', encoding='utf-8') as f_in:
            logs = [line.strip() for line in f_in.readlines() if line.strip()]

        if not logs:
            print("警告：日志文件为空")
            return

        with open(self.output_csv, 'w', encoding='utf-8', newline='') as f_out:
            writer = csv.writer(f_out)
            writer.writerow(["时间", "用户", "问题", "描述"])
            writer.writerows(logs)

        print("✅ 已导出到 " + self.output_csv + "（{} 条记录）".format(len(logs)))


if __name__ == "__main__":
    ExportCSV().run()
'''

    example_file.write_text(example_content, encoding='utf-8')
    print(f"  ✅ 示例代码已生成: {example_file.relative_to(project_dir)}")

    # 创建对应的测试文件
    test_file = project_dir / "tests" / f"test_{feature_key.replace('-', '_')}.py"
    test_file.parent.mkdir(exist_ok=True)

    test_content = f'''"""
测试模块：{feature_key}

功能：
{chr(10).join(f"- {desc}" for desc in feature_description)}
"""

import pytest
from examples.{feature_key.replace('-', '_')} import ExportCSV


def test_export_csv_basic():
    """测试基础导出功能"""
    exporter = ExportCSV()

    # 可以在这里添加真实的测试逻辑
    assert hasattr(exporter, 'run')
'''

    test_file.write_text(test_content, encoding='utf-8')
    print(f"  ✅ 测试文件已生成: {test_file.relative_to(project_dir)}")


def auto_commit(project_dir: Path, feature_key: str, change_type: str = "feat",
                scope: str = None, description: str = "添加新功能") -> str:
    """
    自动 Commit（严格遵循 Conventional Commits）

    Conventional Commits 格式：
        <type>(<scope>): <description>

        [optional body]

        [optional footer(s)]

    Args:
        project_dir: 项目目录
        feature_key: 功能 key（例：'fix-console-log-residue'）
        change_type: 变更类型（feat/fix/docs/style/refactor/test/chore/build/ci/perf）
        scope: 影响范围（默认从 feature_key 提取）
        description: 简短描述（必填）

    Returns:
        commit message
    """
    # 1. 验证 change_type
    valid_types = ["feat", "fix", "docs", "style", "refactor", "test", "chore", "build", "ci", "perf"]
    if change_type not in valid_types:
        print(f"  ⚠️  无效的 change_type '{change_type}'，回退到 'feat'")
        change_type = "feat"

    # 2. 提取 scope（如果未提供）
    if not scope:
        # 从 feature_key 提取首词
        words = feature_key.replace("-", "_").split("_")
        # 去掉 "fix" / "feat" 前缀
        words = [w for w in words if w not in ("fix", "feat")]
        scope = words[0] if words else "core"

    # 3. 限制 description 长度（≤72 字符）
    if len(description) > 72:
        description = description[:69] + "..."

    # 4. 构造完整 commit message
    message = f"{change_type}({scope}): {description}\n\n"

    # 5. body（根据 change_type 智能生成）
    if change_type == "feat":
        message += "- 添加实现代码\n"
        message += "- 添加单元测试\n"
    elif change_type == "fix":
        message += "- 修复 bug\n"
        message += "- 添加回归测试\n"
    elif change_type == "docs":
        message += "- 更新文档\n"
    elif change_type == "refactor":
        message += "- 重构代码（不改行为）\n"
    elif change_type == "test":
        message += "- 添加/修改测试\n"
    elif change_type == "chore":
        message += "- 配置/工具更新\n"
    elif change_type == "perf":
        message += "- 性能优化\n"
    else:
        message += "- 更新代码\n"

    # 6. footer：关联 Issue（如果有）
    if "fix" in feature_key or "bug" in description.lower():
        # Bug 修复尝试关联 Issue（自动获取最近创建的 fix Issue）
        message += "\nRefs: #auto-detect-from-current-branch\n"

    # 7. 限制总长度（避免 commit message 过长）
    if len(message) > 500:
        message = message[:497] + "..."

    print(f"\n💾 自动提交（Conventional Commits）:")
    print(f"  {message}")
    print()

    run_cmd(["git", "add", "."], workdir=project_dir)
    run_cmd(["git", "commit", "-m", message], workdir=project_dir)

    print("  ✅ Commit 已提交")
    return message


def auto_create_pr(project_dir: Path, feature_key: str, docs_updated: bool) -> Tuple[bool, str]:
    """
    自动创建 PR

    返回：(成功状态, PR URL) 或 (False, 错误信息)
    """
    print(f"\n🔗 自动创建 PR ({feature_key})")

    change_type = "docs" if docs_updated else "feat"
    title = f"[{change_type}] {feature_key}: 实现导出 CSV 功能"

    # 生成 PR body（含自动勾选的 checkbox）
    # 注意：gh CLI 的 --body 支持的多行需要 --body-file
    pr_description = generate_pr_body(feature_key, "", docs_updated)
    pr_description_file = project_dir / ".temp_pr_body.md"
    pr_description_file.write_text(pr_description, encoding='utf-8')

    try:
        result = gh_command([
            "pr", "create",
            "--title", title,
            "--body-file", str(pr_description_file),
            "--base", DEFAULT_BRANCH,
            "--head", f"@me:{feature_key}/v1"
        ])

        result.check_output()

        pr_url = result.stdout.strip()
        print(f"  ✅ PR 已创建: {pr_url}")

        return True, pr_url

    except subprocess.CalledProcessError as e:
        if "A pull request already exists" in e.stderr:
            print("  ⚠️  PR 已存在，跳过")
            return False, ""
        raise


def auto_wait_and_check_ci(project_dir: Path, feature_key: str, docs_updated: bool):
    """
    自动等待 CI 通过 + 检查门禁

    docs_updated: 如果文档已改，则这是"正常流程"
    """
    print(f"\n⏳ 等待 CI 运行...")

    max_attempts = 30
    wait_time = 30  # 秒

    for attempt in range(max_attempts):
        print(f"  [尝试 {attempt + 1}/{max_attempts}] 等待 {wait_time} 秒...")
        run_cmd(["sleep", str(wait_time)], timeout=wait_time + 10)

        result = gh_command([
            "pr", "view", "--json checks", "--jq '.checks'"], check=False)

        # 这里简化判断，实际需要解析 JSON
        # 应该有类似：status = "completed/running/queued"

    print("  ❌ CI 检查失败")
    return False


def auto_check_docs_sync(project_dir: Path, base_branch: str = "main") -> Tuple[bool, List[str]]:
    """
    检查文档同步（模拟 check-docs-sync.sh）

    返回：(是否更新, 文档列表)
    """
    print(f"\n📄 检查文档同步...")

    docs_updated, docs_to_update = check_docs_sync(project_dir, base_branch)

    if docs_updated:
        print(f"  ✅ 文档已更新: {docs_to_update}")
    else:
        print(f"  ❌ 未检测到 5 份核心文档变更")
        print(f"  建议：请手动更新以下 5 份核心文档：")
        print(f"    - docs/PRD.md")
        print(f"    - CHANGELOG.md")
        print(f"    - README.md")
        print(f"    - docs/AGENTS.md")
        print(f"    - docs/INTEGRATION.md")

    return docs_updated, docs_to_update


def analyze_git_status(project_dir: Path, base_branch: str = "main") -> Tuple[bool, List[str]]:
    """
    分析 git 状态（手动调用 check-docs-sync.sh）

    返回：(是否更新, 文档列表)
    """
    # 这里先简化实现，实际应该调用 check-docs-sync.sh
    # 但由于我们的自动化目标是"零交互"，所以这里用模拟逻辑
    return auto_check_docs_sync(project_dir, base_branch)


# ===== 主流程 =====

def main():
    parser = argparse.ArgumentParser(description="Agent Feature Workflow — 极强自动化工单脚本")
    parser.add_argument("feature_key", help="功能关键帧，如 export-support-log-csv")
    parser.add_argument("--description", nargs="+", default=[], help="功能描述（第一项为标题）")
    parser.add_argument("--project", default="prompt-engine", help="项目目录名（默认 prompt-engine）")
    parser.add_argument("--simulate", action="store_true", help="模拟运行（不实际创建 Issue/PR）")
    # 覆盖项目目录（让脚本可以通过 command line 覆盖）
    parser.add_argument("--workdir", help="工作目录")

    args = parser.parse_args()

    # 验证参数
    if not args.description:
        print("错误：请提供功能描述")
        sys.exit(1)

    # 确定工作目录
    if args.workdir:
        project_dir = Path(args.workdir)
    else:
        project_dir = Path(__file__).parent.parent / args.project

    if not project_dir.exists():
        print(f"错误：项目目录不存在: {project_dir}")
        sys.exit(1)

    print("=" * 70)
    print("🤖 Agent Feature Workflow — 极强自动化工单脚本")
    print("=" * 70)
    print(f"功能关键帧: {args.feature_key}")
    print(f"功能描述: {' '.join(args.description)}")
    print(f"工作目录: {project_dir}")

    # 自动检测默认分支（main 或 master）
    result = run_cmd(["git", "symbolic-ref", "refs/remotes/origin/HEAD"], workdir=project_dir, check=False)
    if result.returncode == 0 and result.stdout.strip():
        # 格式：refs/remotes/origin/main 或 refs/remotes/origin/master
        default_branch = result.stdout.strip().split("/")[-1]
    else:
        # 回退：尝试 main，失败则用 master
        result_main = run_cmd(["git", "rev-parse", "--verify", "main"], workdir=project_dir, check=False)
        default_branch = "main" if result_main.returncode == 0 else "master"

    print(f"  📌 默认分支: {default_branch}")

    # 检查是否已切换到默认分支
    current_branch = get_current_branch()

    if current_branch != default_branch:
        print(f"  ⚠️  当前不在 {default_branch} 分支 ({current_branch})，将自动切换")
        checkout_result = run_cmd(["git", "checkout", default_branch], workdir=project_dir, check=False)
        if checkout_result.returncode != 0:
            print(f"  ⚠️  无法切换到 {default_branch} 分支，继续在 {current_branch} 分支上工作")
            default_branch = current_branch  # 用当前分支代替

    # 拉取最新代码（失败时仅警告，不中断）
    print(f"\n🔄 拉取最新代码...")
    pull_result = run_cmd(["git", "pull", "origin", default_branch], workdir=project_dir, check=False)
    if pull_result.returncode != 0:
        print(f"  ⚠️  拉取失败（可能网络问题），但继续执行")
        print(f"  💡 你可以稍后手动 `git pull origin {default_branch}`")

    # 自动创建 Issue
    if not args.simulate:
        issue_number = auto_create_issue(args.feature_key, args.description)
    else:
        issue_number = 9998  # 模拟号
        print(f"\n📝 自动创建 Issue（模拟）: #{issue_number}")

    # 自动创建分支
    branch_name = auto_create_branch(args.feature_key, default_branch)

    # 自动写代码（TDD）
    print(f"\n🔍 进入目录: {project_dir}")
    auto_write_code(project_dir, args.feature_key, args.description)

    # 自动 Commit（Conventional Commits）
    # 根据 feature_key 自动推断 change_type
    if args.feature_key.startswith("fix-") or "fix" in args.feature_key:
        change_type = "fix"
    elif args.feature_key.startswith("docs-"):
        change_type = "docs"
    elif args.feature_key.startswith("chore-"):
        change_type = "chore"
    elif args.feature_key.startswith("refactor-"):
        change_type = "refactor"
    else:
        change_type = "feat"

    commit_message = auto_commit(
        project_dir,
        args.feature_key,
        change_type=change_type,
        description=f"实现{args.description[0] if args.description else '新功能'}"
    )

    # 分析文档同步（5 份核心文档）
    docs_updated, docs_to_update = analyze_git_status(project_dir, default_branch)

    # 自动创建 PR
    if not args.simulate:
        pr_success, pr_url = auto_create_pr(project_dir, args.feature_key, docs_updated)
        if not pr_success or not pr_url:
            print("❌ PR 创建失败或已存在")
            sys.exit(1)
    else:
        pr_url = f"https://github.com/Colinchiu007/{args.project}/pull/9999"
        docs_updated = False
        print(f"\n🔗 自动创建 PR（模拟）: {pr_url}")

    # 自动等待 CI + 检查门禁
    # 这里暂时简化，实际应该用 GitHub API 轮询 CI 状态
    print(f"\n⏳ 等待 CI 运行...")

    # 最终报告
    print("\n" + "=" * 70)
    print("✅ Agent Feature Workflow — 自动化工单完成")
    print("=" * 70)
    print(f"功能: {' '.join(args.description)}")
    print(f"Issue:  https://github.com/Colinchiu007/{args.project}/issues/{issue_number}")
    print(f"PR:     {pr_url}")
    print(f"分支:   {branch_name}")
    print(f"文件变更:")

    files_diff = run_cmd(["git", "diff", "--name-only", f"origin/{default_branch}"],
                        workdir=project_dir).stdout.strip().split("\n")
    for f in files_diff:
        print(f"  - {f}")

    if docs_updated:
        print(f"\n✅ 5 份核心文档已同步（PRD/CHANGELOG/README/AGENTS/INTEGRATION）")
        print("💡 可以直接在 GitHub 上合并 PR")
    else:
        print(f"\n⚠️  未检测到 5 份核心文档变更")
        print(f"💡 请在 GitHub 网页上手动更新 docs/PRD.md/CHANGELOG.md/README.md/docs/AGENTS.md/docs/INTEGRATION.md")
        print(f"然后点击 PR 页面上的 'Re-run workflow' 按钮，等 CI 通过后再合并")
    # 清理临时文件
    (project_dir / ".temp_pr_body.md").unlink(missing_ok=True)


if __name__ == "__main__":
    main()